spring:

  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres?user=postgres.kzoqorcgyatwmoafkfcb&password=RFUVc4SIHz87TnlP
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # 정적 자원 설정(CSS, JS, 이미지)
  web:
    resources:
      staticLocations: classpath:/static/

  # 라이브 리로드 설정
  devtools:
    livereload:
      enabled: true

# 수파베이스
supabase:
  url: https://kzoqorcgyatwmoafkfcb.supabase.co
  key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6b3FvcmNneWF0d21vYWZrZmNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTA4NDg3MDQsImV4cCI6MjAyNjQyNDcwNH0.sOC91NnK94dqgloyKq5LKqH9nwyVrrUXgQJJn0whyZg
